/*Q7,	* * * * *
	*       *
	* * * * *
	*       *
	*       *

		   */
  #include<stdio.h>
  #include<conio.h>
  void main(){
int i;
  clrscr();


  for(i=1;i<=5;i++){

  if(i==1||i==3){
	printf("* * * * *\n");


  }else{
	printf("*       *\n");

      }
    }
    printf("\n\n");

    // Q
    for(i=1;i<=6;i++){

    if(i==1||i==5){
	printf(" * * * ");
	}
	else if (i==2||i==3||i==4)
	{
		printf("*      *");
		}else {
		printf("      *\n        * *");
		}printf("\n");
		}
		printf("\n\n");
//W









  getch();}